### ISSUE TITLE
exec(statement).first() it returns tuple.

### ISSUE THREAD

**Issue by adpmhel24** [tiangolo/sqlmodel#325]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
statement = select(models.SystemUser).where(models.SystemUser.email == email)
result = db.execute(statement)
system_user = result.first()
```

### Description

Why .first() returns a type tuple?

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

3.93

**Comment by Giuzzilla** [comment]
Perhaps you meant that it returns a tuple?

If that's the case that's the standard SQLAlchemy return, which happens in case you use SQLAlchemy's `select` / `Session` and the `.execute` method.

If you want to get only the actual `SystemUser` instance, you should do `session.exec(statement)` using exclusively the `select` / `Session` imported from sqlmodel and `.exec` instead of `.execute`. This is documented: https://sqlmodel.tiangolo.com/tutorial/select/#sqlmodels-sessionexec

If you prefer to use SQLAlchemy's sessions or select and you still want to avoid the tuple, you'll need to add `.scalars()`, e.g.: `system_user = result.scalars().first()`

**Comment by adpmhel24** [comment]
> Perhaps you meant that it returns a tuple?
> 
> If that's the case this the standard SQLAlchemy 1.4/2.x return, which happens in case you use SQLAlchemy's `select` / `Session` and the `.execute` method.
> 
> If you want to get only the actual `SystemUser` instance, you should do `session.exec(statement)` using exclusively the `select` / `Session` imported from sqlmodel and `.exec` instead of `.execute`. I suggest to read the dedicated sqlmodel documentation on this step: https://sqlmodel.tiangolo.com/tutorial/select/#sqlmodels-sessionexec
> 
> If you prefer to use SQLAlchemy's sessions or select and you still want to avoid the tuple, you'll need to add `.scalars()`, e.g.: `system_user = result.scalars().first()` (you might want to read the 1.4/2.x SQLAlchemy guide for this: https://docs.sqlalchemy.org/en/14/tutorial/data_select.html#selecting-orm-entities-and-columns)

I already did session.exec(statement).first() but the return type was still tuple.
